-- CreateEnum
CREATE TYPE "UserType" AS ENUM ('HELPER', 'SEEKER', 'ADMIN');
CREATE TYPE "VerificationStatus" AS ENUM ('PENDING', 'VERIFIED', 'SUSPENDED', 'REVOKED');
CREATE TYPE "ExperienceLevel" AS ENUM ('BEGINNER', 'INTERMEDIATE', 'EXPERT');
CREATE TYPE "SessionType" AS ENUM ('VOICE', 'VIDEO', 'CHAT');
CREATE TYPE "SessionStatus" AS ENUM ('REQUESTED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DISPUTED');
CREATE TYPE "PaymentMethod" AS ENUM ('VODAFONE_CASH', 'ORANGE_CASH', 'ETISALAT_CASH', 'CREDIT_CARD', 'MEEZA', 'WALLET_BALANCE');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'ESCROWED', 'RELEASED', 'REFUNDED', 'FAILED');
CREATE TYPE "DisputeStatus" AS ENUM ('OPEN', 'IN_MEDIATION', 'RESOLVED', 'ESCALATED', 'CLOSED');
CREATE TYPE "NotificationChannel" AS ENUM ('IN_APP', 'EMAIL', 'SMS');
CREATE TYPE "NotificationType" AS ENUM (
  'SESSION_REQUEST','SESSION_ACCEPTED','SESSION_DECLINED','SESSION_REMINDER',
  'SESSION_STARTED','SESSION_COMPLETED','SESSION_CANCELLED',
  'PAYMENT_RECEIVED','PAYMENT_FAILED','PAYOUT_INITIATED','PAYOUT_COMPLETED',
  'LOW_WALLET_BALANCE','REFUND_PROCESSED','VERIFICATION_APPROVED',
  'VERIFICATION_REJECTED','NEW_REVIEW','SECURITY_ALERT','PLATFORM_ANNOUNCEMENT'
);
